knp_paginator:
    page_range: 5                      # Número de páginas que se muestran en la barra de navegación
    default_options:
        page_name: page                # Nombre del parámetro de consulta para el número de página
        sort_field_name: sort          # Nombre del parámetro de consulta para el campo de ordenación
        sort_direction_name: direction # Nombre del parámetro de consulta para la dirección de ordenación
        distinct: true                 # Garantiza que los resultados no se dupliquen
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'