controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

logout:
    path: /logout

add_to_cart:
    path: /carrito/agregar/{id}
    controller: App\Controller\CarritoController::agregarProducto
    methods: [POST]

carrito:
    path: /carrito
    controller: App\Controller\CarritoController::mostrarCarrito
    methods: [GET]

carrito_update:
    path: /carrito/update/{id}
    controller: App\Controller\CarritoController@update
    methods: ['POST']

carrito_remove:
    path: /carrito/remove/{id}
    controller: 'App\Controller\CarritoController::eliminarArticulo'
    methods: ['GET']
    
admin_productos:
    path: /admin/productos
    controller: App\Controller\ProductosController::index

admin_productos_nuevo:
    path: /admin/productos/nuevo
    controller: App\Controller\ProductosController::nuevo

admin_productos_editar:
    path: /admin/productos/{id}/editar
    controller: App\Controller\ProductosController::editar

admin_productos_eliminar:
    path: /admin/productos/{id}/eliminar
    controller: App\Controller\ProductosController::eliminar
